alter table PROJECTTEST_PRISONER add constraint FK_PROJECTTEST_PRISONER_ON_CELL foreign key (CELL_ID) references PROJECTTEST_CELLS(ID);
create index IDX_PROJECTTEST_PRISONER_ON_CELL on PROJECTTEST_PRISONER (CELL_ID);
